Current watcher
Programming-TRIGON/RobotCodePreSeason2024 pull request #3
Opened 2023-10-30 19:03 UTC by Nummun14

I've tried making the time part of the current watcher, I'm not sure how I'm gonna do the rest. and I don't know how to use the runnable, or how to use the notifie.

2023-10-31 16:07 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    double prevTime;
rename this to previousTime
And why isn't this private?

2023-10-31 16:13 UTC, levyishai requested changes

2023-10-31 16:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    double prevTime;
rename this to previousTime
And why isn't this private?

2023-10-31 16:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    public void currentWatcher(Runnable runnable, Supplier<Integer> current, int maxCurrent, Supplier<Double> time){
1. Rename `time` to something like `timeThreshold` 
2. Rename `current` to `currentSupplier`.
3. Why is time a supplier? 
4. This is not a constructor and will not function as one since it returns void and doesn't have the exact name of the class.

2023-10-31 16:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +        Notifier notifier = new Notifier(runnable);
Is the runnable really what you want to run every cycle?

2023-10-31 16:13 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +        double difference = currentTime - prevTime;
1. Move all the current checking into their own method.
2. What do all these lines achieve?

2023-10-31 16:48 UTC, Nummun14 commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    public void currentWatcher(Runnable runnable, Supplier<Integer> current, int maxCurrent, Supplier<Double> time){
did the first 3. unsure what u want me to change with the 4th. do you want me to change the name of the function? or something else,

2023-11-01 09:25 UTC, Nummun14 commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +        Notifier notifier = new Notifier(runnable);
the only thing it let's me put there is the runnable. I want to run the check every cycle but I don't know how to do that

2023-11-01 09:27 UTC, Nummun14 commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +        double difference = currentTime - prevTime;
1. ok
2. u said u wanted the difference and the current time so we not the exact time the current overflowed

2023-11-01 09:29 UTC, Nummun14 commented
אני מתקשה פה ואני לא מבין הכל. אפשר להיפגש בסדנה מתישהו?

2023-11-02 15:15 UTC, levyishai requested changes

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> + * A class that checks if the current past a certain limit for a certain amount of time.
1. You didn't mention the runnable.
2. a certain *current* limit
3. passed*

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * Checks the current every 0.02 seconds, and it passes runs a runnable.
Start this doc with something like "Construct a new CurrentWatcher that will check the current every 0.02 seconds."

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    private double bellowCurrentTime;
Non-final should be declared after finals. 
below*

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * @param runnable        what will run if the current passes it's limit
the runnable to run if the...

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * @param currentSupplier the current
a supplier for the motor's current

2023-11-02 15:15 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * @param timeThreshold   the time
Explain a bit more about the time threshold

2023-11-02 15:16 UTC, levyishai requested changes

2023-11-02 15:16 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    private boolean isBellowCurrentLimit() {
below*

2023-11-02 15:16 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +
Extra newlines

2023-11-02 15:16 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +        if (didPassTimeThreshold())
I would advise putting a whitespace between these two

2023-11-02 15:27 UTC, levyishai requested changes

2023-11-02 15:27 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * Construct a new CurrentWatcher that will Check the current every 0.02 seconds, and if the current passes runs a runnable.
Constructs*
will check -> checks
if the current passes?

2023-11-02 15:27 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * @param timeThreshold   the time since the motor was started
The time since the motor was started?

2023-11-02 15:27 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    private double bellowCurrentTime;
below*

2023-11-02 15:27 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> + * A clas that checks if the current passed a certain current limit for a certain amount of time and if so, runs a runnable.
class*
"checks if the current" maybe something like "the motor's current"
Maybe add a period after the word time, and remove the word "and"

2023-11-02 15:34 UTC, levyishai requested changes

2023-11-02 15:34 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +    private double belowCurrentTime;
time -> timestamp

2023-11-02 15:34 UTC, levyishai commented on src/main/java/frc/trigon/robot/utilities/CurrentWatcher.java
> +     * @param timeThreshold   the time since the current watcher began checking
Rework this

2023-11-02 15:51 UTC, levyishai approved these changes

2023-11-02 15:52 UTC, merged